# Generated by Django 5.1.4 on 2025-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0004_alter_teacherapplication_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherapplication',
            name='document',
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='document',
            field=models.ManyToManyField(blank=True, related_name='teacher_application_documents', to='common.document'),
        ),
    ]
