# Generated by Django 5.1.4 on 2025-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_url',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='common.document'),
        ),
    ]
