# Generated by Django 5.1.4 on 2025-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('courses', '0002_remove_lesson_content_url_lesson_content_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_url',
            field=models.ManyToManyField(blank=True, related_name='lesson_documents', to='common.document'),
        ),
    ]
