# Generated by Django 5.1.4 on 2025-03-23 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField()),
                ('average_score', models.FloatField()),
            ],
            options={
                'verbose_name': 'Activity Metric',
                'verbose_name_plural': 'Activity Metrics',
                'ordering': ['-activity_date'],
            },
        ),
    ]
