# Generated by Django 5.1.4 on 2025-01-12 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField()),
                ('average_score', models.FloatField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_metrics', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Metric',
                'verbose_name_plural': 'Activity Metrics',
                'ordering': ['-activity_date'],
            },
        ),
    ]
