# Generated by Django 5.1.4 on 2025-04-14 22:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymetrics',
            name='average_model_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitymetrics',
            name='average_teacher_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitymetrics',
            name='avg_attempts',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitymetrics',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_metrics', to='courses.course'),
        ),
        migrations.AddField(
            model_name='activitymetrics',
            name='final_efficiency_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activitymetrics',
            name='late_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activitymetrics',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitymetrics',
            name='activity_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activitymetrics',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activitymetrics',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_metrics', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='activitymetrics',
            name='tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
