# Generated by Django 5.1.4 on 2025-01-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_file_url',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer_file_url',
        ),
    ]
