# Generated by Django 5.1.4 on 2025-03-23 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('common', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduleassessment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.module'),
        ),
        migrations.AddField(
            model_name='moduleassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseassessment',
            name='module_assessments',
            field=models.ManyToManyField(related_name='course_assessments', to='assessments.moduleassessment'),
        ),
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.module'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_file_url',
            field=models.ManyToManyField(blank=True, related_name='question_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='assessments.questiontype'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_file_url',
            field=models.ManyToManyField(blank=True, related_name='user_answer_documents', to='common.document'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='moduleassessment',
            unique_together={('module', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassessment',
            unique_together={('course', 'user')},
        ),
    ]
