# Generated by Django 5.1.4 on 2025-01-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_question_question_file_url_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file_url',
            field=models.ManyToManyField(blank=True, related_name='questions', to='common.document'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_file_url',
            field=models.ManyToManyField(blank=True, related_name='user_answers', to='common.document'),
        ),
    ]
