# Generated by Django 5.1.4 on 2025-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_question_question_file_url_and_more'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_file_url',
            field=models.ManyToManyField(blank=True, related_name='question_documents', to='common.document'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_file_url',
            field=models.ManyToManyField(blank=True, related_name='user_answer_documents', to='common.document'),
        ),
    ]
