# Generated by Django 5.1.4 on 2025-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moduleassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
